version: "3"

services:
  my_api:
    build: .
    container_name: my_api
    volumes:
      - ./my_api/:/src/my_api:rw
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
    command: python ./my_api/manage.py runserver 0.0.0.0:8000
      
  database:
    container_name: stripe_db
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT}