# Generated by Django 4.1.6 on 2023-02-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0004_alter_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='count',
            new_name='nmb',
        ),
    ]
