# Generated by Django 4.1.6 on 2023-02-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0006_alter_order_nmb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
